#!/usr/bin/env python3
"""Generate a bilingual (EN-CN alternating) GDPR privacy policy .docx.

Usage: python3 build_docx.py input.json output.docx

Input JSON structure:
{
  "title_en": "...", "title_cn": "...", "date": "...",
  "blocks": [
    {"type": "h1"|"h2", "en": "...", "cn": "..."},
    {"type": "para", "en": "...", "cn": "..."},
    {"type": "note", "text": "..."},
    {"type": "todo", "text": "..."},
    {"type": "disclaimer"}
  ]
}

Formatting: CN 宋体 12pt (小四), EN Times New Roman, 1.5 line spacing,
0.5 line space-after, first-line indent 2 chars. Notes in blue, todos in red bold.
"""
import json
import sys

from docx import Document
from docx.enum.text import WD_ALIGN_PARAGRAPH, WD_LINE_SPACING
from docx.oxml.ns import qn
from docx.shared import Pt, RGBColor

DISCLAIMER_EN = (
    "This document was generated by a compliance drafting assistance tool and "
    "must be reviewed and approved by a qualified lawyer before publication."
)
DISCLAIMER_CN = (
    "本文档由合规起草辅助工具生成，需律师最终审核后方可对外发布。"
)


def set_run_font(run, cn=False, size=12, bold=False, color=None):
    run.font.size = Pt(size)
    run.font.bold = bold
    run.font.name = "Times New Roman"
    rpr = run._element.get_or_add_rPr()
    rfonts = rpr.find(qn("w:rFonts"))
    if rfonts is None:
        rfonts = rpr.makeelement(qn("w:rFonts"), {})
        rpr.append(rfonts)
    rfonts.set(qn("w:ascii"), "Times New Roman")
    rfonts.set(qn("w:hAnsi"), "Times New Roman")
    rfonts.set(qn("w:eastAsia"), "宋体" if cn else "Times New Roman")
    if color:
        run.font.color.rgb = RGBColor(*color)


def set_para_layout(paragraph, indent_chars=200, after_lines=50):
    pf = paragraph.paragraph_format
    pf.line_spacing_rule = WD_LINE_SPACING.ONE_POINT_FIVE
    ppr = paragraph._element.get_or_add_pPr()
    spacing = ppr.find(qn("w:spacing"))
    if spacing is None:
        spacing = ppr.makeelement(qn("w:spacing"), {})
        ppr.append(spacing)
    spacing.set(qn("w:afterLines"), str(after_lines))
    if indent_chars:
        ind = ppr.find(qn("w:ind"))
        if ind is None:
            ind = ppr.makeelement(qn("w:ind"), {})
            ppr.append(ind)
        ind.set(qn("w:firstLineChars"), str(indent_chars))
        ind.set(qn("w:firstLine"), str(int(indent_chars / 100 * 240)))


def add_text_paragraph(doc, text, cn, bold=False, indent=True, color=None,
                       align=None):
    p = doc.add_paragraph()
    set_para_layout(p, indent_chars=200 if indent else 0)
    if align is not None:
        p.alignment = align
    run = p.add_run(text)
    set_run_font(run, cn=cn, bold=bold, color=color)
    return p


def main():
    if len(sys.argv) != 3:
        print(__doc__)
        sys.exit(1)
    with open(sys.argv[1], encoding="utf-8") as f:
        data = json.load(f)

    doc = Document()
    # Normal style baseline
    style = doc.styles["Normal"]
    style.font.name = "Times New Roman"
    style.font.size = Pt(12)
    style.element.rPr.rFonts.set(qn("w:eastAsia"), "宋体")

    title_paras = []
    if data.get("title_en"):
        title_paras.append(
            add_text_paragraph(doc, data["title_en"], cn=False, bold=True,
                               indent=False, align=WD_ALIGN_PARAGRAPH.CENTER))
    if data.get("title_cn"):
        title_paras.append(
            add_text_paragraph(doc, data["title_cn"], cn=True, bold=True,
                               indent=False, align=WD_ALIGN_PARAGRAPH.CENTER))
    if data.get("date"):
        title_paras.append(
            add_text_paragraph(doc, data["date"], cn=False, indent=False,
                               align=WD_ALIGN_PARAGRAPH.CENTER))
    if data.get("date_cn"):
        title_paras.append(
            add_text_paragraph(doc, data["date_cn"], cn=True, indent=False,
                               align=WD_ALIGN_PARAGRAPH.CENTER))
    for p in title_paras:
        for run in p.runs:
            is_meta = p.text in (data.get("date"), data.get("date_cn"))
            run.font.size = Pt(12 if is_meta else 16)

    blue = (0x00, 0x00, 0xFF)
    red = (0xFF, 0x00, 0x00)

    for block in data.get("blocks", []):
        btype = block.get("type", "para")
        if btype in ("h1", "h2"):
            size = 14 if btype == "h1" else 12
            created = []
            if block.get("en"):
                created.append(
                    add_text_paragraph(doc, block["en"], cn=False, bold=True,
                                       indent=False))
            if block.get("cn"):
                created.append(
                    add_text_paragraph(doc, block["cn"], cn=True, bold=True,
                                       indent=False))
            for p in created:
                for run in p.runs:
                    run.font.size = Pt(size)
        elif btype == "para":
            if block.get("en"):
                add_text_paragraph(doc, block["en"], cn=False)
            if block.get("cn"):
                add_text_paragraph(doc, block["cn"], cn=True)
        elif btype == "note":
            add_text_paragraph(doc, block.get("text", ""), cn=True,
                               indent=False, color=blue)
        elif btype == "todo":
            add_text_paragraph(doc, block.get("text", ""), cn=True,
                               bold=True, indent=False, color=red)
        elif btype == "disclaimer":
            add_text_paragraph(doc, DISCLAIMER_EN, cn=False, indent=False)
            add_text_paragraph(doc, DISCLAIMER_CN, cn=True, indent=False)

    doc.save(sys.argv[2])
    print(f"Saved: {sys.argv[2]}")


if __name__ == "__main__":
    main()
